//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextAdventure.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextAdventure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die What do you want to do? ähnelt.
        /// </summary>
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Back to menu. ähnelt.
        /// </summary>
        internal static string Credits_Back {
            get {
                return ResourceManager.GetString("Credits_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This game has been made by Jöran Malek (GPBP914) as first project at SAE Institute Hamburg.
        ///Rules: Console Game, Style of Zorg.
        ///
        ///Idea: Jöran Malek
        ///Programming: Jöran Malek ähnelt.
        /// </summary>
        internal static string Credits_Description {
            get {
                return ResourceManager.GetString("Credits_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        internal static string Credits_Title {
            get {
                return ResourceManager.GetString("Credits_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You interacted with {0}. ähnelt.
        /// </summary>
        internal static string DefaultInteract {
            get {
                return ResourceManager.GetString("DefaultInteract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start over in main menu. ähnelt.
        /// </summary>
        internal static string GameOver_Back {
            get {
                return ResourceManager.GetString("GameOver_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You just finished the game. The following has been added to your finish:
        ///{0} ähnelt.
        /// </summary>
        internal static string GameOver_Description {
            get {
                return ResourceManager.GetString("GameOver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Exit this game. ähnelt.
        /// </summary>
        internal static string GameOver_Quit {
            get {
                return ResourceManager.GetString("GameOver_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You just finished the game. ähnelt.
        /// </summary>
        internal static string GameOver_Title {
            get {
                return ResourceManager.GetString("GameOver_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Action ähnelt.
        /// </summary>
        internal static string Generic_Action {
            get {
                return ResourceManager.GetString("Generic_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Actions ähnelt.
        /// </summary>
        internal static string Generic_Actions {
            get {
                return ResourceManager.GetString("Generic_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} got {1} damage. Health remaining: {2}. ähnelt.
        /// </summary>
        internal static string Generic_GotDamage {
            get {
                return ResourceManager.GetString("Generic_GotDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Health ähnelt.
        /// </summary>
        internal static string Generic_Health {
            get {
                return ResourceManager.GetString("Generic_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}&gt;  ähnelt.
        /// </summary>
        internal static string Generic_InputFormat {
            get {
                return ResourceManager.GetString("Generic_InputFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Inventory ähnelt.
        /// </summary>
        internal static string Generic_Inventory {
            get {
                return ResourceManager.GetString("Generic_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max Health ähnelt.
        /// </summary>
        internal static string Generic_MaxHealth {
            get {
                return ResourceManager.GetString("Generic_MaxHealth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stats ähnelt.
        /// </summary>
        internal static string Generic_Stats {
            get {
                return ResourceManager.GetString("Generic_Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0}
        ///{1}: {2}
        ///{3}: {4} ähnelt.
        /// </summary>
        internal static string Generic_StatsFormat {
            get {
                return ResourceManager.GetString("Generic_StatsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strength ähnelt.
        /// </summary>
        internal static string Generic_Strength {
            get {
                return ResourceManager.GetString("Generic_Strength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The goblin has died. ähnelt.
        /// </summary>
        internal static string Goblin_Died {
            get {
                return ResourceManager.GetString("Goblin_Died", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input {0} is unknown. ähnelt.
        /// </summary>
        internal static string InvalidAction {
            get {
                return ResourceManager.GetString("InvalidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show me credits. ähnelt.
        /// </summary>
        internal static string MainMenu_Credits {
            get {
                return ResourceManager.GetString("MainMenu_Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This is the main menu. Please choose one of the options below to do something more relevant than this ähnelt.
        /// </summary>
        internal static string MainMenu_Description {
            get {
                return ResourceManager.GetString("MainMenu_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit this application. ähnelt.
        /// </summary>
        internal static string MainMenu_Exit {
            get {
                return ResourceManager.GetString("MainMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start adventure! ähnelt.
        /// </summary>
        internal static string MainMenu_Start {
            get {
                return ResourceManager.GetString("MainMenu_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TextAdventure ähnelt.
        /// </summary>
        internal static string MainMenu_Title {
            get {
                return ResourceManager.GetString("MainMenu_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nothing found in translation. ähnelt.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your {0} has been increased to {1}. ähnelt.
        /// </summary>
        internal static string Potion_Message {
            get {
                return ResourceManager.GetString("Potion_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You wake up in a dark room. You can see the silhouette of some objects. One looks like a switch. Another is mid-high and has a round shape. ähnelt.
        /// </summary>
        internal static string Room1_Description_Dark {
            get {
                return ResourceManager.GetString("Room1_Description_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You switched on the light. You are able to see every corner of this room. It is not large. There is a door on the other side. The round silhouette turns out to be a table. There is a glass with a red fluid inside on the table. ähnelt.
        /// </summary>
        internal static string Room1_Description_Light {
            get {
                return ResourceManager.GetString("Room1_Description_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You drunk the glass with red content. You do not feel well and slowly start faltering. ähnelt.
        /// </summary>
        internal static string Room1_Died_DrankGlass {
            get {
                return ResourceManager.GetString("Room1_Died_DrankGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You took the glass and you smell something intense.  ähnelt.
        /// </summary>
        internal static string Room1_Died_TookGlass {
            get {
                return ResourceManager.GetString("Room1_Died_TookGlass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You tried everything, but nothing happened. ähnelt.
        /// </summary>
        internal static string Room1_Fail {
            get {
                return ResourceManager.GetString("Room1_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have toggled the light switch. ähnelt.
        /// </summary>
        internal static string Room1_LightSwitch_TurnOn {
            get {
                return ResourceManager.GetString("Room1_LightSwitch_TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entry Room ähnelt.
        /// </summary>
        internal static string Room1_Title {
            get {
                return ResourceManager.GetString("Room1_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You opened the door and went through it. Something got your attention. It&apos;s a small, grey thing. There in a corner of this room. After some time you recognize a mice in it. Right next to it is a door. On this door stands &quot;Mage&quot; in magical letters. ähnelt.
        /// </summary>
        internal static string Room2_Description {
            get {
                return ResourceManager.GetString("Room2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maybe .. &quot;attack&quot; or &quot;sneak&quot; are what you want to try? ähnelt.
        /// </summary>
        internal static string Room2_Fail {
            get {
                return ResourceManager.GetString("Room2_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Long Hall ähnelt.
        /// </summary>
        internal static string Room2_Title {
            get {
                return ResourceManager.GetString("Room2_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You enter the room called &quot;Mages room&quot;. It is bright and filled with lots of books and wood and stuff. Under a huge amount of books you see a long, blue hat. You move the books away and a mage sees into your eyes.
        ///&quot;Hey, you must be&quot; ähnelt.
        /// </summary>
        internal static string Room3_Description_AskForName {
            get {
                return ResourceManager.GetString("Room3_Description_AskForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die &quot;Okay {0}. There are some rumors that goblins are in the western forests. Please take a look and tell me if they are true.&quot;
        ///You ask him why you are here and where he comes from but the mage answers &quot;You will find out, hopefully&quot;.
        ///&quot;Now go down the stairs. It will bring you straight to the forest. And .. before I forget: You might want to open your inventory and revisit your stats some time.&quot; ähnelt.
        /// </summary>
        internal static string Room3_Description_Quest {
            get {
                return ResourceManager.GetString("Room3_Description_Quest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The mage did not understand you. ähnelt.
        /// </summary>
        internal static string Room3_Fail {
            get {
                return ResourceManager.GetString("Room3_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mages Room ähnelt.
        /// </summary>
        internal static string Room3_Title {
            get {
                return ResourceManager.GetString("Room3_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On your way down to the forest you pass some weapons. Some letters are on the wall telling, that you should take them.
        ///Right after you leave the tower a small goblin falls on your feet. He stands up, takes his sword and swings it in front of you. ähnelt.
        /// </summary>
        internal static string Room4_Description {
            get {
                return ResourceManager.GetString("Room4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die After the goblin died you see a path into the forest which you have not seen before. ähnelt.
        /// </summary>
        internal static string Room4_Progress {
            get {
                return ResourceManager.GetString("Room4_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tower Ground ähnelt.
        /// </summary>
        internal static string Room4_Title {
            get {
                return ResourceManager.GetString("Room4_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die with,me ähnelt.
        /// </summary>
        internal static string StrikeWords {
            get {
                return ResourceManager.GetString("StrikeWords", resourceCulture);
            }
        }
    }
}
